name: define secrets
on:
  page_build:
  
    jobs:
      pages-build-deployment:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
              check-latest: true
          - env:
              CI: true
              API_KEY: ${{ secrets.API_KEY }}
