name: define secrets
on:
  page_build:
jobs:
  pages-build-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          CI: true
          API_KEY: ${{ secrets.API_KEY }}
